from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'payments'

router = DefaultRouter()
router.register(r'', views.PaymentViewSet, basename='payments') # Register PaymentViewSet

urlpatterns = [
    path('', include(router.urls)), # Include URLs generated by the router
    # Example custom action URLs if not handled by @action decorator's detail=True/False routing:
    # path('<uuid:pk>/succeed_payment/', views.PaymentViewSet.as_view({'post': 'succeed_payment'}), name='payment-succeed-payment'),
    # path('<uuid:pk>/fail_payment/', views.PaymentViewSet.as_view({'post': 'fail_payment'}), name='payment-fail-payment'),
]
# Note: The @action decorator with detail=True automatically generates routes like /payments/{pk}/succeed_payment/
# So, explicit paths for succeed_payment and fail_payment might not be needed here if using DRF's default routing for actions.
# If payments-succeed-payment and payments-fail-payment are used in tests, ensure they align with DRF's generated URL names or define them explicitly.
# DefaultRouter generates:
# - /payments/ - list, create
# - /payments/{pk}/ - retrieve, update, partial_update, destroy
# - /payments/{pk}/succeed_payment/ - for @action(detail=True)
# - /payments/{pk}/fail_payment/ - for @action(detail=True)
