from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PaymentViewSet, CreatePaymentIntentView, StripeWebhookView

app_name = 'payments'

router = DefaultRouter()
# The PaymentViewSet is now ReadOnly, so it won't have create/update URLs unless explicitly defined.
# For admin/listing purposes, it's fine.
router.register(r'view', PaymentViewSet, basename='payment-view') # Changed base name to avoid conflict if 'payments' is used for main payment actions

urlpatterns = [
    # URLs for the new views
    path('create-payment-intent/', CreatePaymentIntentView.as_view(), name='create-payment-intent'),
    path('stripe-webhook/', StripeWebhookView.as_view(), name='stripe-webhook'),

    # Include URLs generated by the router for the PaymentViewSet (e.g., /payments/view/, /payments/view/{pk}/)
    path('', include(router.urls)),
]
