"""
Django settings for event_booking_platform_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
# import os # Unused
from pathlib import Path
# import sys # Unused

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Assuming .env file is in the parent directory of settings.py (project root)
# For a structure like:
# project_root/
#   .env
#   app_name/
#     settings.py
# you might need to adjust the path: Path(BASE_DIR).parent / '.env'
# If your .env is in the same directory as manage.py (i.e., project root)
ENV_PATH = BASE_DIR / ".env" # This is /app/event_booking_platform_backend/.env
# Attempt to read .env file from the project root /app/.env as well for dockerized environments
PROJECT_ROOT_ENV_PATH = BASE_DIR.parent / ".env"

if ENV_PATH.exists():
    environ.Env.read_env(str(ENV_PATH))
elif PROJECT_ROOT_ENV_PATH.exists():
    environ.Env.read_env(str(PROJECT_ROOT_ENV_PATH))
else:
    # Silently proceed if .env not found, relying on direct env vars or defaults
    pass

# Stripe API Keys
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="your_stripe_publishable_key_here_default")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="your_stripe_secret_key_here_default")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="your_stripe_webhook_secret_here_default")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This is the primary source for SECRET_KEY, loaded from environment variables or a default.
SECRET_KEY = env(
    "SECRET_KEY",
    default="your-default-secret-key-if-not-in-env- मेक-sure-this-is-very-secret-for-prod",
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is True if the DEBUG environment variable is set to 'True', otherwise False.
DEBUG = env("DEBUG", default=False)

# Remove or comment out the redundant hardcoded SECRET_KEY and DEBUG settings below
# SECRET_KEY = 'django-insecure-gw!vhy+3f_s)ard3$du2a@h433km21=cz0tbigz5u5ar1d!+ak' # Redundant
# DEBUG = True # Redundant, use env('DEBUG', default=False)

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS", default=[]
)  # Load from env, default to empty list


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "core",
    "venues",
    "events",
    "bookings",
    "payments", # Payments app
    # Authentication apps
    "rest_framework.authtoken",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",  # Optional, but good to have for future
    "drf_spectacular",  # API Documentation
]

SITE_ID = 1  # Required by django-allauth

# Django Allauth specific settings (optional, but recommended for dj_rest_auth.registration)
ACCOUNT_EMAIL_VERIFICATION = "none"  # Can be 'optional' or 'mandatory' for development
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email' # Deprecated
ACCOUNT_LOGIN_METHODS = ["username", "email"]  # New setting
# ACCOUNT_EMAIL_REQUIRED = True # Deprecated
# Specify required fields for signup
ACCOUNT_SIGNUP_FIELDS = [
    "email",
    "username",
    "password",
]
# Ensure 'email' and 'username' are required if that's the intent. Default is often just username.
# Example for forcing email with more specific requirements:
# ACCOUNT_SIGNUP_FIELDS = {'email': {'required': True}, 'username': {'required': True}, 'password': {'required': True}}
# For simplicity, let's use the basic list for now. dj-rest-auth might have defaults too.

# ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username' # Default
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300 # 5 minutes

AUTH_USER_MODEL = "core.User"  # Custom User model

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Django Allauth middleware
]

ROOT_URLCONF = "event_booking_platform_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], # Add project-level templates directory
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "event_booking_platform_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Defaulting to SQLite for development simplicity.
# For production, PostgreSQL is recommended. Example using django-environ:
# DATABASES = {'default': env.db('DATABASE_URL', default='postgres://user:pass@host:port/dbname')}
# Ensure the appropriate adapter (e.g., psycopg2-binary or psycopg2) is installed for PostgreSQL.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# if 'test' in sys.argv: # Keep test db as in-memory sqlite
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': ':memory:',
#     }

# Cache
# https://docs.djangoproject.com/en/5.0/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",  # Optional, for in-memory cache, helps isolate if multiple processes
    }
    # To use Redis (ensure 'django-redis' is installed via pip):
    # 'default': env.cache('REDIS_URL', default='redis://localhost:6379/1')
    # Example REDIS_URL in .env: REDIS_URL=redis://user:password@hostname:port/database_number
}

# Email Configuration for Development
# https://docs.djangoproject.com/en/dev/topics/email/#console-backend
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # Default for dev

# PRODUCTION EMAIL CONFIGURATION (Example using django-environ, to be uncommented and configured in production)
# EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
# EMAIL_HOST = env('EMAIL_HOST', default='localhost')
# EMAIL_PORT = env.int('EMAIL_PORT', default=25) # Use env.int for integer values
# EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
# EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=False) # Use env.bool for boolean values
# EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False) # Mutually exclusive with EMAIL_USE_TLS
# DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')
# SERVER_EMAIL = env('SERVER_EMAIL', default='root@localhost') # For error notifications


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Event Booking Platform API",
    "DESCRIPTION": "API for managing venues, events, and bookings for the Event Booking SaaS Platform.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # Set to True to view schema in Swagger UI/Redoc
    "SWAGGER_UI_DIST": "SIDECAR",  # Use a CDN for Swagger UI files
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",  # Use a CDN for Redoc files
    # Add more settings as needed:
    # 'COMPONENT_SPLIT_REQUEST': True,
    # 'SORT_OPERATION_PARAMETERS': False,
}

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
