# Generated by Django 5.2.1 on 2025-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID, if applicable.', max_length=255, null=True),
        ),
    ]
