# Generated by Django 5.2.1 on 2025-06-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
