# Generated by Django 5.2.1 on 2025-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity for this event. If blank, venue capacity will be used.', null=True),
        ),
    ]
