# Generated by Django 5.2.1 on 2025-06-16 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_max_capacity'),
        ('venues', '0003_venue_venues_venu_name_6dcdaa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='events_even_name_d5901c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time'], name='events_even_start_t_0e446b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue', 'start_time'], name='events_even_venue_i_23b7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='events_even_organiz_266ef7_idx'),
        ),
    ]
