# Generated by Django 5.2.1 on 2025-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('customer', 'Customer'), ('organizer', 'Event Organizer'), ('venue_manager', 'Venue Manager')], default='customer', help_text='The primary role of the user on the platform.', max_length=20, verbose_name='Role'),
        ),
    ]
