# Generated by Django 5.0.7 on 2024-07-25 12:00

from django.db import migrations

ROLES = [
    ('REGULAR_USER', 'Regular User'),
    ('VENUE_MANAGER', 'Venue Manager'),
    ('EVENT_ORGANIZER', 'Event Organizer'),
]

def populate_roles(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    for role_name, role_verbose_name in ROLES:
        Role.objects.get_or_create(name=role_name)

def delete_roles(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    for role_name, _ in ROLES:
        Role.objects.filter(name=role_name).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role_remove_user_roles_user_roles'),
    ]

    operations = [
        migrations.RunPython(populate_roles, delete_roles),
    ]
