# Generated by Django 5.2.1 on 2025-06-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_initial_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EVENT_ORGANIZER', 'Event Organizer'), ('VENUE_MANAGER', 'Venue Manager'), ('CUSTOMER', 'Customer')], max_length=50, unique=True),
        ),
    ]
