# Generated by Django 5.2.1 on 2025-06-10 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who owns or manages this venue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
