# Generated by Django 5.2.1 on 2025-06-16 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='venues_venu_name_6dcdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['address'], name='venues_venu_address_dd9a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['capacity'], name='venues_venu_capacit_6a742b_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['is_available'], name='venues_venu_is_avai_b6f4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['owner'], name='venues_venu_owner_i_eef73e_idx'),
        ),
    ]
